version: "3.8"

networks:
  rabbit-network:
    name: rabbit-network
    driver: bridge

services:
  rabbitlocal:
    image: rabbitmq:3.12-management
    container_name: rabbitlocal
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    environment:
      - RABBITMQ_DEFAULT_USER=username
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - rabbit-network
